[target.xtensa-esp32s2-none-elf]
runner = "espflash flash --before no-reset --no-stub"


[env]
ESP_LOG="INFO"
ESP_HAL_CONFIG_PLACE_SPI_MASTER_DRIVER_IN_RAM = "true"

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

target = "xtensa-esp32s2-none-elf"

[unstable]
build-std = ["core", "alloc"]
